### ISSUE TITLE
Text input broken

### ISSUE THREAD

**Issue by skhome** [ulfschneider/spitfire#1]
Since a few days I can't add new tasks or edit existing ones. Moving or changing colors is still working. Has there been any change that might have caused this?

**Comment by hwestphal** [comment]
I could reproduce the error locally. Root cause for this seems to be the unsynchronized time between client and server. There is a timeout for text input fields of 2 minutes, i.e. when the server time is behind the client time more than these 2 minutes the text input field will be immediately closed.

**Comment by ulfschneider** [comment]
Many thanks for the feedback and sorry for the late response on the first issue report. I´ve restarted the server to fix the clock issue and spitfire is back into working mode again. If I do not hear anything from you during this week, I assume the issue is fixed for you and I will close the issue.

**Comment by skhome** [comment]
Works again. Thank you.
